Sources/hal/ADC.c File Reference
#include `ADC.h`
*
Functions
void vfnInitAdc (ePorts port, U08 u08Pin)
void vfnADC_IRQ (void)
Variables
U16 U16vADCValue
Detailed Description
Author
Date
Function Documentation
void vfnADC_IRQ (void)
Definition at line 70 of file ADC.c.
References ADC0_RA, ADC0_SC1A, ADC_SC1_COCO_MASK, and U16vADCValue.
void vfnInitAdc (ePorts port, U08 u08Pin)
Definition at line 54 of file ADC.c.
References ADC, ADC0_CFG1, ADC0_SC1A, ADC0_SC3, ADC_CFG1_MODE_MASK, ADC_SC1_ADCH_MASK, ADC_SC3_ADCO_MASK, ADC_SC3_AVGE_MASK, SIM_SCGC6, SIM_SCGC6_ADC0_MASK, vfnConfigPortRegPins(), and vfnInitGpio().
Referenced by vfnInitTemperatura().
Variable Documentation
U16 U16vADCValue
Definition at line 46 of file ADC.c.
Referenced by vfnADC_IRQ().