Sources/hal/ADC.h File Reference
#include `Types.h`
*
#include `derivative.h`
*
#include `GPIO.h`
*
#include `PORTCfgs.h`
*
Macros
#define ADC 0
Functions
void vfnInitAdc (ePorts port, U08 u08Pin)
Detailed Description
Author
Date
Macro Definition Documentation
#define ADC 0
Definition at line 35 of file ADC.h.
Referenced by vfnInitAdc().
Function Documentation
void vfnInitAdc (ePorts port, U08 u08Pin)
Definition at line 54 of file ADC.c.
References ADC, ADC0_CFG1, ADC0_SC1A, ADC0_SC3, ADC_CFG1_MODE_MASK, ADC_SC1_ADCH_MASK, ADC_SC3_ADCO_MASK, ADC_SC3_AVGE_MASK, SIM_SCGC6, SIM_SCGC6_ADC0_MASK, vfnConfigPortRegPins(), and vfnInitGpio().
Referenced by vfnInitTemperatura().