Sources/hal/GPIO.h File Reference
#include `Types.h`
*
#include `derivative.h`
*
#include `PORTCfgs.h`
*
Macros
#define GPIO 1
#define INPUT 0
#define OUTPUT 1
#define BYTE_MASK 0xFF
Functions
void vfnInitGpio (ePorts port)
void vfnSetGPIOPortPins (ePorts port, U08 u08arrayPins[], U08 u08arrayPinsSize, U08 u08PinsDirection)
void vfnSetBit (ePorts port, U08 u08Bit)
void vfnClearBit (ePorts port, U08 u08Bit)
void vfnSendByte (ePorts port, U08 u08Byte)
U32 vfnReadData (ePorts port)
Macro Definition Documentation
#define BYTE_MASK 0xFF
Definition at line 48 of file GPIO.h.
#define GPIO 1
Definition at line 34 of file GPIO.h.
Referenced by vfnSetGPIOPortPins().
#define INPUT 0
Definition at line 40 of file GPIO.h.
Referenced by vfnInitUltrasonico().
#define OUTPUT 1
Definition at line 46 of file GPIO.h.
Referenced by main(), vfnInitMotors(), vfnInitPantalla(), vfnInitUltrasonico(), and vfnSetGPIOPortPins().
Function Documentation
void vfnClearBit (ePorts port, U08 u08Bit)
Definition at line 109 of file GPIO.c.
References GPIO_PDOR_REG, and U32_CLEAR_BIT.
Referenced by main(), vfnParar(), and vfnSendData().
void vfnInitGpio (ePorts port)
Definition at line 62 of file GPIO.c.
References arrSIM_SCGC5_PORTS, and SIM_SCGC5.
Referenced by hc_sr04_init(), main(), vfnInitAdc(), vfnInitMotors(), vfnInitPantalla(), vfnInitPWM(), and vfnInitUltrasonico().
U32 vfnReadData (ePorts port)
Definition at line 119 of file GPIO.c.
References GPIO_PDOR_REG.
void vfnSendByte (ePorts port, U08 u08Byte)
Definition at line 123 of file GPIO.c.
References GPIO_PDOR_REG.
Referenced by vfnSendData().
void vfnSetBit (ePorts port, U08 u08Bit)
Definition at line 99 of file GPIO.c.
References GPIO_PDOR_REG, and U32_SET_BIT.
Referenced by main(), vfnAdelante(), vfnAtras(), vfnDerecha(), vfnIzquierda(), and vfnSendData().
void vfnSetGPIOPortPins (ePorts port, U08 u08arrayPins[], U08 u08arrayPinsSize, U08 u08PinsDirection)
Definition at line 73 of file GPIO.c.
References GPIO, GPIO_PDDR_PDD, GPIO_PDDR_REG, GPIO_PSOR_PTSO, GPIO_PSOR_REG, OUTPUT, and vfnConfigPortRegPins().
Referenced by main(), vfnInitMotors(), vfnInitPantalla(), and vfnInitUltrasonico().