Sources/hal/GPIO.c File Reference
#include `GPIO.h`
*
Functions
void vfnInitGpio (ePorts port)
void vfnSetGPIOPortPins (ePorts port, U08 u08arrayPins[], U08 u08arrayPinsSize, U08 u08PinsDirection)
void vfnSetBit (ePorts port, U08 u08Bit)
void vfnClearBit (ePorts port, U08 u08Bit)
U32 vfnReadData (ePorts port)
void vfnSendByte (ePorts port, U08 u08Byte)
Variables
U32 arrSIM_SCGC5_PORTS [] = {SIM_SCGC5_PORTA_MASK, SIM_SCGC5_PORTB_MASK, SIM_SCGC5_PORTC_MASK, SIM_SCGC5_PORTD_MASK, SIM_SCGC5_PORTE_MASK}
GPIO_MemMapPtr arrGPIOBasePtrs [] = GPIO_BASE_PTRS
Function Documentation
void vfnClearBit (ePorts port, U08 u08Bit)
Definition at line 109 of file GPIO.c.
References GPIO_PDOR_REG, and U32_CLEAR_BIT.
Referenced by main(), vfnParar(), and vfnSendData().
void vfnInitGpio (ePorts port)
Definition at line 62 of file GPIO.c.
References arrSIM_SCGC5_PORTS, and SIM_SCGC5.
Referenced by hc_sr04_init(), main(), vfnInitAdc(), vfnInitMotors(), vfnInitPantalla(), vfnInitPWM(), and vfnInitUltrasonico().
U32 vfnReadData (ePorts port)
Definition at line 119 of file GPIO.c.
References GPIO_PDOR_REG.
void vfnSendByte (ePorts port, U08 u08Byte)
Definition at line 123 of file GPIO.c.
References GPIO_PDOR_REG.
Referenced by vfnSendData().
void vfnSetBit (ePorts port, U08 u08Bit)
Definition at line 99 of file GPIO.c.
References GPIO_PDOR_REG, and U32_SET_BIT.
Referenced by main(), vfnAdelante(), vfnAtras(), vfnDerecha(), vfnIzquierda(), and vfnSendData().
void vfnSetGPIOPortPins (ePorts port, U08 u08arrayPins[], U08 u08arrayPinsSize, U08 u08PinsDirection)
Definition at line 73 of file GPIO.c.
References GPIO, GPIO_PDDR_PDD, GPIO_PDDR_REG, GPIO_PSOR_PTSO, GPIO_PSOR_REG, OUTPUT, and vfnConfigPortRegPins().
Referenced by main(), vfnInitMotors(), vfnInitPantalla(), and vfnInitUltrasonico().
Variable Documentation
GPIO_MemMapPtr arrGPIOBasePtrs[] = GPIO_BASE_PTRS
Definition at line 53 of file GPIO.c.
U32 arrSIM_SCGC5_PORTS[] = {SIM_SCGC5_PORTA_MASK, SIM_SCGC5_PORTB_MASK, SIM_SCGC5_PORTC_MASK, SIM_SCGC5_PORTD_MASK, SIM_SCGC5_PORTE_MASK}
Definition at line 47 of file GPIO.c.
Referenced by vfnInitGpio().