Sources/hil/HC-SR04.c File Reference
#include `HC-SR04.h`
*
Functions
void hc_sr04_init (void)
U16 hc_sr04_read (void)
void hc_sr04_trigger (void)
void TPM0_IRQHandler (void)
void TPM1_IRQHandler (void)
void TPM2_IRQHandler (void)
Variables
volatile U08 ready = 0
volatile U32 start = 0
volatile U32 end = 0
volatile U32 OvF = 0
U32 tpm_clk_hz = 0
Detailed Description
Author
Date
Function Documentation
void hc_sr04_init (void)
Definition at line 58 of file HC-SR04.c.
References enable_irq(), EnableInterrupts, GPIO_PCOR_PTCO, GPIO_PDDR_PDD, GPIOC_PCOR, GPIOC_PDDR, INT_TPM0, PORT_PCR_MUX, PORT_PCR_PE_MASK, PORTC, PORTC_PCR8, PORTD, PORTD_PCR1, PS_16, set_irq_priority(), sysinit(), TPM0_BASE_PTR, TPM_CH_init_hcsr04(), TPM_CLK, tpm_clk_hz, TPM_CLK_MODE(), TPM_CNT_DIS, TPM_IC_BOTH, TPM_init_IC(), TPM_MODULE_HC_SR04, TPM_PLLFLL, and vfnInitGpio().
Referenced by main().
U16 hc_sr04_read (void)
Definition at line 83 of file HC-SR04.c.
References end, hc_sr04_trigger(), OvF, ready, RSLTN, SNSR_1CM_hz, start, TPM0_BASE_PTR, TPM_CLK, tpm_clk_hz, TPM_CLK_MODE(), and TPM_CNT_DIS.
Referenced by main(), and vfnCarCheckFrontFree().
void hc_sr04_trigger (void)
Definition at line 101 of file HC-SR04.c.
References GPIO_PCOR_PTCO, GPIO_PSOR_PTSO, GPIOC_PCOR, and GPIOC_PSOR.
Referenced by hc_sr04_read().
void TPM0_IRQHandler (void)
Definition at line 110 of file HC-SR04.c.
References end, OvF, ready, start, TPM0_BASE_PTR, TPM0_C1SC, TPM0_CNT, TPM0_SC, TPM_clear_counter(), TPM_CnSC_CHF_MASK, TPM_MODULE_HC_SR04, and TPM_SC_TOF_MASK.
Referenced by NMI_Handler().
void TPM1_IRQHandler (void)
Definition at line 134 of file HC-SR04.c.
References TPM1_SC, and TPM_SC_TOF_MASK.
void TPM2_IRQHandler (void)
Definition at line 140 of file HC-SR04.c.
References TPM2_SC, and TPM_SC_TOF_MASK.
Variable Documentation
volatile U32 end = 0
Definition at line 48 of file HC-SR04.c.
Referenced by hc_sr04_read(), and TPM0_IRQHandler().
volatile U32 OvF = 0
Definition at line 49 of file HC-SR04.c.
Referenced by hc_sr04_read(), and TPM0_IRQHandler().
volatile U08 ready = 0
Definition at line 46 of file HC-SR04.c.
Referenced by hc_sr04_read(), and TPM0_IRQHandler().
volatile U32 start = 0
Definition at line 47 of file HC-SR04.c.
Referenced by hc_sr04_read(), and TPM0_IRQHandler().
U32 tpm_clk_hz = 0
Definition at line 50 of file HC-SR04.c.
Referenced by hc_sr04_init(), and hc_sr04_read().