Sources/hil/HC-SR04.h File Reference
#include `derivative.h`
*
#include `Types.h`
*
#include `nvic.h`
*
#include `GPIO.h`
*
#include `sysinit.h`
*
#include `tpm_hc-sr04.h`
*
Macros
#define TPM_MODULE_HC_SR04 0xFFFF
#define SNSR_1CM_hz 18518
#define RSLTN 1000
Functions
void hc_sr04_init (void)
U16 hc_sr04_read (void)
void hc_sr04_trigger (void)
Detailed Description
Author
Date
Macro Definition Documentation
#define RSLTN 1000
Definition at line 38 of file HC-SR04.h.
Referenced by hc_sr04_read(), main(), and vfnCarCheckFrontFree().
#define SNSR_1CM_hz 18518
Definition at line 37 of file HC-SR04.h.
Referenced by hc_sr04_read().
#define TPM_MODULE_HC_SR04 0xFFFF
Definition at line 36 of file HC-SR04.h.
Referenced by hc_sr04_init(), and TPM0_IRQHandler().
Function Documentation
void hc_sr04_init (void)
Definition at line 58 of file HC-SR04.c.
References enable_irq(), EnableInterrupts, GPIO_PCOR_PTCO, GPIO_PDDR_PDD, GPIOC_PCOR, GPIOC_PDDR, INT_TPM0, PORT_PCR_MUX, PORT_PCR_PE_MASK, PORTC, PORTC_PCR8, PORTD, PORTD_PCR1, PS_16, set_irq_priority(), sysinit(), TPM0_BASE_PTR, TPM_CH_init_hcsr04(), TPM_CLK, tpm_clk_hz, TPM_CLK_MODE(), TPM_CNT_DIS, TPM_IC_BOTH, TPM_init_IC(), TPM_MODULE_HC_SR04, TPM_PLLFLL, and vfnInitGpio().
Referenced by main().
U16 hc_sr04_read (void)
Definition at line 83 of file HC-SR04.c.
References end, hc_sr04_trigger(), OvF, ready, RSLTN, SNSR_1CM_hz, start, TPM0_BASE_PTR, TPM_CLK, tpm_clk_hz, TPM_CLK_MODE(), and TPM_CNT_DIS.
Referenced by main(), and vfnCarCheckFrontFree().
void hc_sr04_trigger (void)
Definition at line 101 of file HC-SR04.c.
References GPIO_PCOR_PTCO, GPIO_PSOR_PTSO, GPIOC_PCOR, and GPIOC_PSOR.
Referenced by hc_sr04_read().