Sources/hil/MotorDvr.c File Reference
#include `MotorDvr.h`
*
Functions
void vfnInitMotors (ePorts port, U08 MI_1, U08 MI_2, U08 MD_1, U08 MD_2)
void vfnParar (void)
void vfnAdelante (void)
void vfnAtras (void)
void vfnIzquierda (void)
void vfnDerecha (void)
Variables
U08 MoI_1 = NULL
U08 MoI_2 = NULL
U08 MoD_1 = NULL
U08 MoD_2 = NULL
ePorts myPort
Detailed Description
Author
Date
Function Documentation
void vfnAdelante (void)
Definition at line 78 of file MotorDvr.c.
References MoD_1, MoD_2, MoI_1, MoI_2, myPort, vfnParar(), and vfnSetBit().
Referenced by main(), and vfnCarMoveFront().
void vfnAtras (void)
Definition at line 86 of file MotorDvr.c.
References MoD_1, MoD_2, MoI_1, MoI_2, myPort, vfnParar(), and vfnSetBit().
Referenced by main(), and vfnCarMoveBack().
void vfnDerecha (void)
Definition at line 101 of file MotorDvr.c.
References MoD_1, MoD_2, MoI_1, MoI_2, myPort, vfnParar(), and vfnSetBit().
Referenced by main(), and vfnCarTurn().
void vfnInitMotors (ePorts port, U08 MI_1, U08 MI_2, U08 MD_1, U08 MD_2)
Definition at line 57 of file MotorDvr.c.
References MD_1, MD_2, MI_1, MI_2, MoD_1, MoD_2, MoI_1, MoI_2, myPort, OUTPUT, vfnInitGpio(), and vfnSetGPIOPortPins().
Referenced by main().
void vfnIzquierda (void)
Definition at line 94 of file MotorDvr.c.
References MoD_1, MoD_2, MoI_1, MoI_2, myPort, vfnParar(), and vfnSetBit().
Referenced by main(), and vfnCarTurn().
void vfnParar (void)
Definition at line 69 of file MotorDvr.c.
References MoD_1, MoD_2, MoI_1, MoI_2, myPort, and vfnClearBit().
Referenced by vfnAdelante(), vfnAtras(), vfnCarStop(), vfnDerecha(), and vfnIzquierda().
Variable Documentation
U08 MoD_1 = NULL
Definition at line 46 of file MotorDvr.c.
Referenced by vfnAdelante(), vfnAtras(), vfnDerecha(), vfnInitMotors(), vfnIzquierda(), and vfnParar().
U08 MoD_2 = NULL
Definition at line 46 of file MotorDvr.c.
Referenced by vfnAdelante(), vfnAtras(), vfnDerecha(), vfnInitMotors(), vfnIzquierda(), and vfnParar().
U08 MoI_1 = NULL
Definition at line 46 of file MotorDvr.c.
Referenced by vfnAdelante(), vfnAtras(), vfnDerecha(), vfnInitMotors(), vfnIzquierda(), and vfnParar().
U08 MoI_2 = NULL
Definition at line 46 of file MotorDvr.c.
Referenced by vfnAdelante(), vfnAtras(), vfnDerecha(), vfnInitMotors(), vfnIzquierda(), and vfnParar().
ePorts myPort
Definition at line 48 of file MotorDvr.c.
Referenced by vfnAdelante(), vfnAtras(), vfnDerecha(), vfnInitMotors(), vfnIzquierda(), and vfnParar().