Sources/hal/PORTCfgs.h File Reference
#include `Types.h`
*
#include `derivative.h`
*
Enumerations
enum ePorts {
*
PORTA,
PORTB,
PORTC,
PORTD,
*
PORTE
 }
Functions
void vfnConfigPortRegPins (ePorts port, U08 u08Pines[], U08 u08arrayPinsSize, U08 u08MuxType)
Detailed Description
Author
Date
Enumeration Type Documentation
enum ePorts
Enumerator
PORTA
PORTB
PORTC
PORTD
PORTE
Definition at line 39 of file PORTCfgs.h.
Function Documentation
void vfnConfigPortRegPins (ePorts port, U08 u08Pines[], U08 u08arrayPinsSize, U08 u08MuxType)
Definition at line 54 of file PORTCfgs.c.
References PORT_PCR_MUX, and PORT_PCR_REG.
Referenced by vfnInitAdc(), vfnSelectChannelPortPin(), and vfnSetGPIOPortPins().