Sources/hal/PORTCfgs.c File Reference
#include `PORTCfgs.h`
*
Functions
void vfnConfigPortRegPins (ePorts port, U08 u08Pines[], U08 u08arrayPinsSize, U08 u08MuxType)
Variables
PORT_MemMapPtr arrPortBasePtrs [] = PORT_BASE_PTRS
Detailed Description
Author
Date
Function Documentation
void vfnConfigPortRegPins (ePorts port, U08 u08Pines[], U08 u08arrayPinsSize, U08 u08MuxType)
Definition at line 54 of file PORTCfgs.c.
References PORT_PCR_MUX, and PORT_PCR_REG.
Referenced by vfnInitAdc(), vfnSelectChannelPortPin(), and vfnSetGPIOPortPins().
Variable Documentation
PORT_MemMapPtr arrPortBasePtrs[] = PORT_BASE_PTRS
Definition at line 46 of file PORTCfgs.c.