Sources/hil/PWM.h File Reference
#include `derivative.h`
*
#include `Types.h`
*
#include `tpm.h`
*
#include `GPIO.h`
*
Functions
void vfnInitPWM (ePorts port, U08 u08Pin)
void vfnMoveLeft ()
void vfnMoveCenter ()
void vfnMoveRight ()
Detailed Description
Author
Date
Function Documentation
void vfnInitPWM (ePorts port, U08 u08Pin)
Definition at line 54 of file PWM.c.
References EDGE_PWM, PS_8, TPM1_BASE_PTR, TPM_CH_init(), TPM_CLK, TPM_init_PWM(), TPM_MODULE, TPM_PLLFLL, TPM_PWM_H, vfnInitGpio(), and vfnSelectChannelPortPin().
Referenced by main().
void vfnMoveCenter ()
Definition at line 65 of file PWM.c.
References DUTY_MED, and set_pos().
Referenced by vfnCarMoveFront().
void vfnMoveLeft ()
Definition at line 61 of file PWM.c.
References DUTY_MAX, and set_pos().
Referenced by main(), and vfnCarTurnSensorLeft().
void vfnMoveRight ()
Definition at line 69 of file PWM.c.
References DUTY_MIN, and set_pos().
Referenced by vfnCarTurnSensorRight().