Sources/hil/PantallaDvr.h File Reference
#include `GPIO.h`
*
#include `lptmr.h`
*
Macros
#define RS 0
#define E 1
#define PIN_0 0
#define PIN_1 1
#define PIN_2 2
#define PIN_3 3
#define PIN_4 4
#define PIN_5 5
#define PIN_6 6
#define PIN_7 7
#define INSTRUCTION (U08)0
#define DATA (U08)1
#define _15_MSEC 3500
#define _40_USEC 35
#define FIRST_POSITION 0x80
Functions
void vfnInitPantalla (void)
void vfnSendData (U08 u08Type, U08 u08Code)
void vfnDelayPantalla (U32 u32Delay)
Detailed Description
Author
Date
Macro Definition Documentation
#define _15_MSEC 3500
Definition at line 44 of file PantallaDvr.h.
#define _40_USEC 35
Definition at line 45 of file PantallaDvr.h.
#define DATA (U08)1
Definition at line 43 of file PantallaDvr.h.
Referenced by vfnSendData().
#define E 1
Definition at line 33 of file PantallaDvr.h.
Referenced by vfnSendData().
#define FIRST_POSITION 0x80
Definition at line 46 of file PantallaDvr.h.
#define INSTRUCTION (U08)0
Definition at line 42 of file PantallaDvr.h.
Referenced by vfnInitPantalla(), and vfnSendData().
#define PIN_0 0
Definition at line 34 of file PantallaDvr.h.
#define PIN_1 1
Definition at line 35 of file PantallaDvr.h.
#define PIN_2 2
Definition at line 36 of file PantallaDvr.h.
#define PIN_3 3
Definition at line 37 of file PantallaDvr.h.
#define PIN_4 4
Definition at line 38 of file PantallaDvr.h.
#define PIN_5 5
Definition at line 39 of file PantallaDvr.h.
#define PIN_6 6
Definition at line 40 of file PantallaDvr.h.
#define PIN_7 7
Definition at line 41 of file PantallaDvr.h.
#define RS 0
Definition at line 32 of file PantallaDvr.h.
Referenced by vfnSendData().
Function Documentation
void vfnDelayPantalla (U32 u32Delay)
Definition at line 97 of file PantallaDvr.c.
void vfnInitPantalla (void)
Definition at line 59 of file PantallaDvr.c.
References InitializeLCD, INSTRUCTION, OUTPUT, PORTB, PORTC, u08PinesControl, u08PinesDatos, vfnInitGpio(), vfnSendData(), and vfnSetGPIOPortPins().
void vfnSendData (U08 u08Type, U08 u08Code)
Definition at line 76 of file PantallaDvr.c.
References DATA, E, INSTRUCTION, PORTB, PORTC, RS, time_delay_ms(), vfnClearBit(), vfnSendByte(), and vfnSetBit().
Referenced by vfnInitPantalla().