Sources/hil/PantallaDvr.c File Reference
#include `PantallaDvr.h`
*
Functions
void vfnInitPantalla (void)
void vfnSendData (U08 u08Type, U08 u08Code)
void vfnDelayPantalla (U32 u32Delay)
Variables
U08 u08PinesControl [] = {RS, E}
U08 u08PinesDatos [] = {PIN_0, PIN_1, PIN_2, PIN_3, PIN_4, PIN_5, PIN_6, PIN_7}
const unsigned char InitializeLCD [5] = {0x38, 0x0C, 0x01}
Detailed Description
Author
Date
Function Documentation
void vfnDelayPantalla (U32 u32Delay)
Definition at line 97 of file PantallaDvr.c.
void vfnInitPantalla (void)
Definition at line 59 of file PantallaDvr.c.
References InitializeLCD, INSTRUCTION, OUTPUT, PORTB, PORTC, u08PinesControl, u08PinesDatos, vfnInitGpio(), vfnSendData(), and vfnSetGPIOPortPins().
void vfnSendData (U08 u08Type, U08 u08Code)
Definition at line 76 of file PantallaDvr.c.
References DATA, E, INSTRUCTION, PORTB, PORTC, RS, time_delay_ms(), vfnClearBit(), vfnSendByte(), and vfnSetBit().
Referenced by vfnInitPantalla().
Variable Documentation
const unsigned char InitializeLCD[5] = {0x38, 0x0C, 0x01}
Definition at line 51 of file PantallaDvr.c.
Referenced by vfnInitPantalla().
U08 u08PinesControl[] = {RS, E}
Definition at line 47 of file PantallaDvr.c.
Referenced by vfnInitPantalla().
U08 u08PinesDatos[] = {PIN_0, PIN_1, PIN_2, PIN_3, PIN_4, PIN_5, PIN_6, PIN_7}
Definition at line 48 of file PantallaDvr.c.
Referenced by vfnInitPantalla().