Sources/hal/TIMER.c File Reference
#include `derivative.h`
*
#include `Timer.h`
*
#include `LEDDvr.h`
*
Functions
void vfnTimerInit (void)
void vfnSetTimer (U32 u32LDVAL)
void vfnStopTimer (void)
void vfnPit1_IRQ (void)
Detailed Description
Author
Date
Function Documentation
void vfnPit1_IRQ (void)
Definition at line 97 of file TIMER.c.
References vfnLedToogle(), and vfnSetTimer().
void vfnSetTimer (U32 u32LDVAL)
Definition at line 72 of file TIMER.c.
References PIT_LDVAL1, PIT_TCTRL1, PIT_TCTRL_TEN_MASK, and PIT_TFLG1.
Referenced by vfnPit1_IRQ().
void vfnStopTimer (void)
Definition at line 86 of file TIMER.c.
References PIT_TCTRL1, and PIT_TCTRL_TEN_MASK.
void vfnTimerInit (void)
Definition at line 56 of file TIMER.c.
References NVIC_ISER, PIT_LDVAL1, PIT_MCR, PIT_TCTRL1, PIT_TCTRL_TEN_MASK, PIT_TCTRL_TIE_MASK, SIM_SCGC6, and SIM_SCGC6_PIT_MASK.