Project_Settings/Startup_Code/kinetis_sysinit.c File Reference
#include `kinetis_sysinit.h`
*
#include `derivative.h`
*
Functions
void __thumb_startup (void)
void Default_Handler ()
void __init_hardware ()
void NMI_Handler ()
Variables
uint32_t __vector_table []
unsigned long _estack
Function Documentation
void __init_hardware ()
===========================================================================
Reset handler
Definition at line 40 of file kinetis_sysinit.c.
References __vector_table, KINETIS_WDOG_DISABLED_CTRL, SCB_VTOR, and SIM_COPC.
Referenced by __thumb_startup().
void __thumb_startup (void)
Definition at line 171 of file __arm_start.c.
References __call_static_initializers(), __init_hardware(), __init_registers(), __init_user(), argv, main(), and zero_fill_bss().
Referenced by __iar_program_start(), and NMI_Handler().
void Default_Handler ()
===========================================================================
Default interrupt handler
Definition at line 30 of file kinetis_sysinit.c.
Referenced by NMI_Handler().
void NMI_Handler ()
Definition at line 49 of file kinetis_sysinit.c.
References __thumb_startup(), _estack, Default_Handler(), and TPM0_IRQHandler().
Variable Documentation
uint32_t __vector_table[]
===========================================================================
External declarations
Referenced by __init_hardware().
unsigned long _estack
Referenced by NMI_Handler().