Sources/hal/lptmr.c File Reference
#include `lptmr.h`
*
Functions
void time_delay_ms (unsigned int count_val)
void lptmr_isr (void)
void lptmr_init (int count, int clock_source)
Variables
char tick = 0
int re_init_clk
int clock_freq_hz
Function Documentation
void lptmr_init (int count, int clock_source)
Definition at line 72 of file lptmr.c.
References LPTMR0_CMR, LPTMR0_CSR, LPTMR0_PSR, LPTMR_CMR_COMPARE, LPTMR_CSR_TCF_MASK, LPTMR_CSR_TEN_MASK, LPTMR_CSR_TFC_MASK, LPTMR_CSR_TIE_MASK, LPTMR_CSR_TMS_MASK, LPTMR_CSR_TPP_MASK, LPTMR_CSR_TPS, LPTMR_PSR_PBYP_MASK, LPTMR_PSR_PCS, LPTMR_PSR_PRESCALE, SIM_SCGC5, and SIM_SCGC5_LPTMR_MASK.
void lptmr_isr (void)
Definition at line 56 of file lptmr.c.
References LPTMR0_CSR, LPTMR_CSR_TCF_MASK, LPTMR_CSR_TEN_MASK, LPTMR_CSR_TIE_MASK, and tick.
void time_delay_ms (unsigned int count_val)
Definition at line 30 of file lptmr.c.
References LPTMR0_CMR, LPTMR0_CSR, LPTMR0_PSR, LPTMR_CSR_TCF_MASK, LPTMR_CSR_TEN_MASK, LPTMR_PSR_PBYP_MASK, LPTMR_PSR_PCS, SIM_SCGC5, and SIM_SCGC5_LPTMR_MASK.
Referenced by main(), vfnCarCheckFrontFree(), and vfnSendData().
Variable Documentation
int clock_freq_hz
int re_init_clk
char tick = 0
Definition at line 15 of file lptmr.c.
Referenced by lptmr_isr().