Sources/hal/lptmr.h File Reference
#include `derivative.h`
*
Macros
#define LPTMR_USE_IRCLK 0
#define LPTMR_USE_LPOCLK 1
#define LPTMR_USE_ERCLK32 2
#define LPTMR_USE_OSCERCLK 3
Functions
void time_delay_ms (unsigned int count_val)
void lptmr_isr (void)
void lptmr_init (int count, int clock_source)
Macro Definition Documentation
#define LPTMR_USE_ERCLK32 2
Definition at line 17 of file lptmr.h.
#define LPTMR_USE_IRCLK 0
Definition at line 15 of file lptmr.h.
#define LPTMR_USE_LPOCLK 1
Definition at line 16 of file lptmr.h.
#define LPTMR_USE_OSCERCLK 3
Definition at line 18 of file lptmr.h.
Function Documentation
void lptmr_init (int count, int clock_source)
Definition at line 72 of file lptmr.c.
References LPTMR0_CMR, LPTMR0_CSR, LPTMR0_PSR, LPTMR_CMR_COMPARE, LPTMR_CSR_TCF_MASK, LPTMR_CSR_TEN_MASK, LPTMR_CSR_TFC_MASK, LPTMR_CSR_TIE_MASK, LPTMR_CSR_TMS_MASK, LPTMR_CSR_TPP_MASK, LPTMR_CSR_TPS, LPTMR_PSR_PBYP_MASK, LPTMR_PSR_PCS, LPTMR_PSR_PRESCALE, SIM_SCGC5, and SIM_SCGC5_LPTMR_MASK.
void lptmr_isr (void)
Definition at line 56 of file lptmr.c.
References LPTMR0_CSR, LPTMR_CSR_TCF_MASK, LPTMR_CSR_TEN_MASK, LPTMR_CSR_TIE_MASK, and tick.
void time_delay_ms (unsigned int count_val)
Definition at line 30 of file lptmr.c.
References LPTMR0_CMR, LPTMR0_CSR, LPTMR0_PSR, LPTMR_CSR_TCF_MASK, LPTMR_CSR_TEN_MASK, LPTMR_PSR_PBYP_MASK, LPTMR_PSR_PCS, SIM_SCGC5, and SIM_SCGC5_LPTMR_MASK.
Referenced by main(), vfnCarCheckFrontFree(), and vfnSendData().