Sources/app/main.c File Reference
History: 20130207_1635 :
#include `derivative.h`
*
#include `Types.h`
*
#include `MotorDvr.h`
*
#include `PantallaDvr.h`
*
#include `PWM.h`
*
#include `HC-SR04.h`
*
#include `lptmr.h`
*
#include `GPIO.h`
*
Macros
#define MI_1 30
#define MI_2 29
#define MD_1 23
#define MD_2 22
#define SENSOR_LEFT 0
#define SENSOR_RIGHT 1
#define SENSOR_BLOCK 2
#define DELAY_TURN_DIRECTION 100000
#define DELAY_PREPARE_MOVEMENT 100000
#define DELAY_MOVEMENT_BACK 100000
#define DELAY_SENSOR 100000
#define MOTOR_DRIVER 1
#define TEMPERATURA 2
#define SERVO_MOTOR 3
#define PANTALLA 4
#define ULTRASONICO 5
#define DEBBUG_STATUS 6
#define PRODUCTIVO 7
#define TEST PRODUCTIVO
Enumerations
enum eMoveCarStates {
*
CAR_STOP,
CAR_CHECK_FRONT_FREE,
CAR_MOVE_FRONT,
CAR_TURN_SENSOR_LEFT,
*
CAR_TURN_SENSOR_RIGHT,
CAR_TURN,
CAR_MOVE_BACK
 }
Functions
void vfnCarStop (void)
void vfnCarCheckFrontFree (void)
void vfnCarMoveFront (void)
void vfnCarTurnSensorLeft (void)
void vfnCarTurnSensorRight (void)
void vfnCarTurn (void)
void vfnCarMoveBack (void)
int main (void)
Variables
eMoveCarStates carState = CAR_CHECK_FRONT_FREE
void(* vfnStateMachineFuncPtrCar [])(void) = {vfnCarStop, vfnCarCheckFrontFree, vfnCarMoveFront, vfnCarTurnSensorLeft, vfnCarTurnSensorRight, vfnCarTurn, vfnCarMoveBack}
U16 read = 0
U16 cm = 0
volatile U32 u32Delay = DELAY_TURN_DIRECTION
volatile U32 u32DelayPrepareToMove = DELAY_PREPARE_MOVEMENT
volatile U32 u32DelaySensor = DELAY_SENSOR
volatile U32 u32DelayBack = DELAY_MOVEMENT_BACK
U08 u08turnSensor = SENSOR_LEFT
U08 u08needToTurnCar = 0
Detailed Description
History: 20130207_1635 :
Author
Date
Macro Definition Documentation
#define DEBBUG_STATUS 6
Definition at line 100 of file main.c.
#define DELAY_MOVEMENT_BACK 100000
Definition at line 87 of file main.c.
Referenced by vfnCarMoveBack().
#define DELAY_PREPARE_MOVEMENT 100000
Definition at line 81 of file main.c.
Referenced by vfnCarMoveFront().
#define DELAY_SENSOR 100000
Definition at line 93 of file main.c.
Referenced by vfnCarTurnSensorLeft(), and vfnCarTurnSensorRight().
#define DELAY_TURN_DIRECTION 100000
Definition at line 75 of file main.c.
Referenced by vfnCarCheckFrontFree(), and vfnCarTurn().
#define MD_1 23
Definition at line 44 of file main.c.
Referenced by main(), and vfnInitMotors().
#define MD_2 22
Definition at line 50 of file main.c.
Referenced by main(), and vfnInitMotors().
#define MI_1 30
Definition at line 32 of file main.c.
Referenced by main(), and vfnInitMotors().
#define MI_2 29
Definition at line 38 of file main.c.
Referenced by main(), and vfnInitMotors().
#define MOTOR_DRIVER 1
Definition at line 95 of file main.c.
#define PANTALLA 4
Definition at line 98 of file main.c.
#define PRODUCTIVO 7
Definition at line 101 of file main.c.
#define SENSOR_BLOCK 2
Definition at line 68 of file main.c.
Referenced by vfnCarCheckFrontFree().
#define SENSOR_LEFT 0
Definition at line 56 of file main.c.
Referenced by vfnCarCheckFrontFree(), vfnCarTurn(), and vfnCarTurnSensorLeft().
#define SENSOR_RIGHT 1
Definition at line 62 of file main.c.
Referenced by vfnCarCheckFrontFree(), vfnCarTurn(), and vfnCarTurnSensorRight().
#define SERVO_MOTOR 3
Definition at line 97 of file main.c.
#define TEMPERATURA 2
Definition at line 96 of file main.c.
#define TEST PRODUCTIVO
Definition at line 102 of file main.c.
#define ULTRASONICO 5
Definition at line 99 of file main.c.
Enumeration Type Documentation
enum eMoveCarStates
Enumerator
CAR_STOP
CAR_CHECK_FRONT_FREE
CAR_MOVE_FRONT
CAR_TURN_SENSOR_LEFT
CAR_TURN_SENSOR_RIGHT
CAR_TURN
CAR_MOVE_BACK
Definition at line 110 of file main.c.
Function Documentation
int main (void)
Definition at line 157 of file main.c.
References carState, cm, hc_sr04_init(), hc_sr04_read(), MD_1, MD_2, MI_1, MI_2, OUTPUT, PORTA, PORTE, read, RSLTN, time_delay_ms(), u32Delay, vfnAdelante(), vfnAtras(), vfnClearBit(), vfnDerecha(), vfnInitGpio(), vfnInitMotors(), vfnInitPWM(), vfnIzquierda(), vfnMoveLeft(), vfnSetBit(), vfnSetGPIOPortPins(), and vfnStateMachineFuncPtrCar.
void vfnCarCheckFrontFree (void)
Definition at line 232 of file main.c.
References CAR_MOVE_BACK, CAR_MOVE_FRONT, CAR_STOP, CAR_TURN, carState, cm, DELAY_TURN_DIRECTION, hc_sr04_read(), read, RSLTN, SENSOR_BLOCK, SENSOR_LEFT, SENSOR_RIGHT, time_delay_ms(), u08needToTurnCar, u08turnSensor, and u32Delay.
void vfnCarMoveBack (void)
Definition at line 308 of file main.c.
References CAR_CHECK_FRONT_FREE, carState, DELAY_MOVEMENT_BACK, u32DelayBack, and vfnAtras().
void vfnCarMoveFront (void)
Definition at line 257 of file main.c.
References CAR_CHECK_FRONT_FREE, carState, DELAY_PREPARE_MOVEMENT, u32DelayPrepareToMove, vfnAdelante(), and vfnMoveCenter().
void vfnCarStop (void)
Definition at line 227 of file main.c.
References CAR_TURN_SENSOR_LEFT, carState, and vfnParar().
void vfnCarTurn (void)
Definition at line 295 of file main.c.
References CAR_MOVE_FRONT, carState, DELAY_TURN_DIRECTION, SENSOR_LEFT, SENSOR_RIGHT, u08turnSensor, u32Delay, vfnDerecha(), and vfnIzquierda().
void vfnCarTurnSensorLeft (void)
Definition at line 267 of file main.c.
References CAR_CHECK_FRONT_FREE, CAR_TURN_SENSOR_RIGHT, carState, DELAY_SENSOR, SENSOR_LEFT, u08needToTurnCar, u08turnSensor, u32DelaySensor, and vfnMoveLeft().
void vfnCarTurnSensorRight (void)
Definition at line 281 of file main.c.
References CAR_CHECK_FRONT_FREE, CAR_MOVE_BACK, carState, DELAY_SENSOR, SENSOR_RIGHT, u08needToTurnCar, u08turnSensor, u32DelaySensor, and vfnMoveRight().
Variable Documentation
eMoveCarStates carState = CAR_CHECK_FRONT_FREE
Definition at line 138 of file main.c.
Referenced by main(), vfnCarCheckFrontFree(), vfnCarMoveBack(), vfnCarMoveFront(), vfnCarStop(), vfnCarTurn(), vfnCarTurnSensorLeft(), and vfnCarTurnSensorRight().
U16 cm = 0
Definition at line 149 of file main.c.
Referenced by main(), and vfnCarCheckFrontFree().
U16 read = 0
Definition at line 149 of file main.c.
Referenced by main(), and vfnCarCheckFrontFree().
U08 u08needToTurnCar = 0
Definition at line 151 of file main.c.
Referenced by vfnCarCheckFrontFree(), vfnCarTurnSensorLeft(), and vfnCarTurnSensorRight().
U08 u08turnSensor = SENSOR_LEFT
Definition at line 151 of file main.c.
Referenced by vfnCarCheckFrontFree(), vfnCarTurn(), vfnCarTurnSensorLeft(), and vfnCarTurnSensorRight().
volatile U32 u32Delay = DELAY_TURN_DIRECTION
Definition at line 150 of file main.c.
Referenced by main(), vfnCarCheckFrontFree(), and vfnCarTurn().
volatile U32 u32DelayBack = DELAY_MOVEMENT_BACK
Definition at line 150 of file main.c.
Referenced by vfnCarMoveBack().
volatile U32 u32DelayPrepareToMove = DELAY_PREPARE_MOVEMENT
Definition at line 150 of file main.c.
Referenced by vfnCarMoveFront().
volatile U32 u32DelaySensor = DELAY_SENSOR
Definition at line 150 of file main.c.
Referenced by vfnCarTurnSensorLeft(), and vfnCarTurnSensorRight().
void(* vfnStateMachineFuncPtrCar[])(void) = {vfnCarStop, vfnCarCheckFrontFree, vfnCarMoveFront, vfnCarTurnSensorLeft, vfnCarTurnSensorRight, vfnCarTurn, vfnCarMoveBack}
Definition at line 143 of file main.c.
Referenced by main().