Sources/hal/tpm_hc-sr04.h File Reference
#include `Types.h`
*
#include `derivative.h`
*
Macros
#define TPM_PLLFLL 1
#define TPM_OSCERCLK 2
#define TPM_MCGIRCLK 3
#define TPM_CNT_DIS 0
#define TPM_CLK 1
#define TPM_EXT_CLK 2
#define PS_1 0
#define PS_2 1
#define PS_4 2
#define PS_8 3
#define PS_16 4
#define PS_32 5
#define PS_64 6
#define PS_128 7
#define TPM_IC_RISING TPM_CnSC_ELSA_MASK
#define TPM_IC_FALLING TPM_CnSC_ELSB_MASK
#define TPM_IC_BOTH TPM_CnSC_ELSA_MASK|TPM_CnSC_ELSB_MASK
Functions
U32 TPM_init_IC (TPM_MemMapPtr TPMx, U08 clock_source, U16 modulo, U08 clock_mode, U08 ps)
void TPM_CLK_MODE (TPM_MemMapPtr TPMx, U08 clock_mode)
void TPM_clear_counter (TPM_MemMapPtr TPMx)
void TPM_CH_init_hcsr04 (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
Macro Definition Documentation
#define PS_1 0
Definition at line 22 of file tpm_hc-sr04.h.
#define PS_128 7
Definition at line 29 of file tpm_hc-sr04.h.
#define PS_16 4
Definition at line 26 of file tpm_hc-sr04.h.
#define PS_2 1
Definition at line 23 of file tpm_hc-sr04.h.
#define PS_32 5
Definition at line 27 of file tpm_hc-sr04.h.
#define PS_4 2
Definition at line 24 of file tpm_hc-sr04.h.
#define PS_64 6
Definition at line 28 of file tpm_hc-sr04.h.
#define PS_8 3
Definition at line 25 of file tpm_hc-sr04.h.
#define TPM_CLK 1
Definition at line 19 of file tpm_hc-sr04.h.
#define TPM_CNT_DIS 0
Definition at line 18 of file tpm_hc-sr04.h.
#define TPM_EXT_CLK 2
Definition at line 20 of file tpm_hc-sr04.h.
#define TPM_IC_BOTH TPM_CnSC_ELSA_MASK|TPM_CnSC_ELSB_MASK
Definition at line 33 of file tpm_hc-sr04.h.
Referenced by hc_sr04_init().
#define TPM_IC_FALLING TPM_CnSC_ELSB_MASK
Definition at line 32 of file tpm_hc-sr04.h.
#define TPM_IC_RISING TPM_CnSC_ELSA_MASK
Definition at line 31 of file tpm_hc-sr04.h.
#define TPM_MCGIRCLK 3
Definition at line 16 of file tpm_hc-sr04.h.
#define TPM_OSCERCLK 2
Definition at line 15 of file tpm_hc-sr04.h.
#define TPM_PLLFLL 1
Definition at line 14 of file tpm_hc-sr04.h.
Function Documentation
void TPM_CH_init_hcsr04 (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
Definition at line 55 of file tpm_hc-sr04.c.
References TPM_CnSC_CHIE_MASK, and TPM_CnSC_REG.
Referenced by hc_sr04_init().
void TPM_clear_counter (TPM_MemMapPtr TPMx)
Definition at line 50 of file tpm_hc-sr04.c.
References TPM_CNT_REG.
Referenced by TPM0_IRQHandler().
void TPM_CLK_MODE (TPM_MemMapPtr TPMx, U08 clock_mode)
Definition at line 41 of file tpm_hc-sr04.c.
References TPM_SC_CMOD, and TPM_SC_REG.
Referenced by hc_sr04_init(), and hc_sr04_read().
U32 TPM_init_IC (TPM_MemMapPtr TPMx, U08 clock_source, U16 modulo, U08 clock_mode, U08 ps)
Definition at line 12 of file tpm_hc-sr04.c.
References mcg_clk_hz, SIM_SCGC6, SIM_SCGC6_TPM0_MASK, SIM_SCGC6_TPM1_MASK, SIM_SCGC6_TPM2_MASK, SIM_SOPT2, SIM_SOPT2_TPMSRC, TPM0_BASE_PTR, TPM1_BASE_PTR, TPM_MOD_REG, TPM_SC_CMOD, TPM_SC_PS, TPM_SC_REG, and TPM_SC_TOIE_MASK.
Referenced by hc_sr04_init().