Sources/hal/tpm_hc-sr04.c File Reference
#include `tpm_hc-sr04.h`
*
Functions
U32 TPM_init_IC (TPM_MemMapPtr TPMx, U08 clock_source, U16 modulo, U08 clock_mode, U08 ps)
void TPM_CLK_MODE (TPM_MemMapPtr TPMx, U08 clock_mode)
void TPM_clear_counter (TPM_MemMapPtr TPMx)
void TPM_CH_init_hcsr04 (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
Variables
int mcg_clk_hz
Function Documentation
void TPM_CH_init_hcsr04 (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
Definition at line 55 of file tpm_hc-sr04.c.
References TPM_CnSC_CHIE_MASK, and TPM_CnSC_REG.
Referenced by hc_sr04_init().
void TPM_clear_counter (TPM_MemMapPtr TPMx)
Definition at line 50 of file tpm_hc-sr04.c.
References TPM_CNT_REG.
Referenced by TPM0_IRQHandler().
void TPM_CLK_MODE (TPM_MemMapPtr TPMx, U08 clock_mode)
Definition at line 41 of file tpm_hc-sr04.c.
References TPM_SC_CMOD, and TPM_SC_REG.
Referenced by hc_sr04_init(), and hc_sr04_read().
U32 TPM_init_IC (TPM_MemMapPtr TPMx, U08 clock_source, U16 modulo, U08 clock_mode, U08 ps)
Definition at line 12 of file tpm_hc-sr04.c.
References mcg_clk_hz, SIM_SCGC6, SIM_SCGC6_TPM0_MASK, SIM_SCGC6_TPM1_MASK, SIM_SCGC6_TPM2_MASK, SIM_SOPT2, SIM_SOPT2_TPMSRC, TPM0_BASE_PTR, TPM1_BASE_PTR, TPM_MOD_REG, TPM_SC_CMOD, TPM_SC_PS, TPM_SC_REG, and TPM_SC_TOIE_MASK.
Referenced by hc_sr04_init().
Variable Documentation
int mcg_clk_hz
Definition at line 10 of file sysinit.c.
Referenced by sysinit(), and TPM_init_IC().