Sources/hal/tpm.c File Reference
#include `tpm.h`
*
Functions
void vfnSelectChannelPortPin (ePorts port, U08 u08Pin)
void TPM_init_PWM (TPM_MemMapPtr TPMx, U08 clock_source, U16 module, U08 clock_mode, U08 ps, U08 counting_mode)
void TPM_CH_init (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
void set_TPM_CnV (TPM_MemMapPtr TPMx, U08 channel, U16 value)
void set_pos (U16 duty)
void vfnDelayTpm (U32 u32Delay)
Function Documentation
void set_pos (U16 duty)
Definition at line 44 of file tpm.c.
References set_TPM_CnV(), and TPM1_BASE_PTR.
Referenced by vfnMoveCenter(), vfnMoveLeft(), and vfnMoveRight().
void set_TPM_CnV (TPM_MemMapPtr TPMx, U08 channel, U16 value)
Definition at line 39 of file tpm.c.
References TPM_CnV_REG.
Referenced by set_pos().
void TPM_CH_init (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
Definition at line 34 of file tpm.c.
References TPM_CnSC_REG.
Referenced by vfnInitPWM().
void TPM_init_PWM (TPM_MemMapPtr TPMx, U08 clock_source, U16 module, U08 clock_mode, U08 ps, U08 counting_mode)
Definition at line 14 of file tpm.c.
References SIM_SCGC6, SIM_SCGC6_TPM0_MASK, SIM_SCGC6_TPM1_MASK, SIM_SCGC6_TPM2_MASK, SIM_SOPT2, SIM_SOPT2_TPMSRC, TPM0_BASE_PTR, TPM1_BASE_PTR, TPM_MOD_REG, TPM_SC_CMOD, TPM_SC_CPWMS_MASK, TPM_SC_PS, and TPM_SC_REG.
Referenced by vfnInitPWM().
void vfnDelayTpm (U32 u32Delay)
Definition at line 49 of file tpm.c.
void vfnSelectChannelPortPin (ePorts port, U08 u08Pin)
Definition at line 9 of file tpm.c.
References TPM_MUX, and vfnConfigPortRegPins().
Referenced by vfnInitPWM().