Sources/hal/tpm.h File Reference
#include `Types.h`
*
#include `derivative.h`
*
#include `PORTCfgs.h`
*
#include `GPIO.h`
*
Macros
#define TPM_PLLFLL 1
#define TPM_OSCERCLK 2
#define TPM_MCGIRCLK 3
#define TPM_CNT_DIS 0
#define TPM_CLK 1
#define TPM_EXT_CLK 2
#define PS_1 0
#define PS_2 1
#define PS_4 2
#define PS_8 3
#define PS_16 4
#define PS_32 5
#define PS_64 6
#define PS_128 7
#define TPM_OC_TOGGLE TPM_CnSC_MSA_MASK|TPM_CnSC_ELSA_MASK
#define TPM_OC_CLR TPM_CnSC_MSA_MASK|TPM_CnSC_ELSB_MASK
#define TPM_OC_SET TPM_CnSC_MSA_MASK|TPM_CnSC_ELSA_MASK|TPM_CnSC_ELSB_MASK
#define TPM_OC_OUTL TPM_CnSC_MSB_MASK|TPM_CnSC_MSA_MASK|TPM_CnSC_ELSB_MASK
#define TPM_OC_OUTH TPM_CnSC_MSB_MASK|TPM_CnSC_MSA_MASK|TPM_CnSC_ELSA_MASK
#define TPM_PWM_H TPM_CnSC_MSB_MASK|TPM_CnSC_ELSB_MASK
#define TPM_PWM_L TPM_CnSC_MSB_MASK|TPM_CnSC_ELSA_MASK
#define EDGE_PWM 0
#define CENTER_PWM 1
#define TPM_MODULE 52816
#define DUTY_MIN 1800
#define DUTY_MED 3700
#define DUTY_MAX 5900
#define TPM_MUX 3
#define TIMER 1000000
Functions
void vfnSelectChannelPortPin (ePorts port, U08 u08Pin)
void TPM_init_PWM (TPM_MemMapPtr TPMx, U08 clock_source, U16 module, U08 clock_mode, U08 ps, U08 counting_mode)
void TPM_CH_init (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
void set_TPM_CnV (TPM_MemMapPtr TPMx, U08 channel, U16 value)
void set_pos (U16 angle)
void vfnDelayTpm (U32 u32Delay)
Detailed Description
Author
Date
Macro Definition Documentation
#define CENTER_PWM 1
Definition at line 62 of file tpm.h.
#define DUTY_MAX 5900
Definition at line 73 of file tpm.h.
Referenced by vfnMoveLeft().
#define DUTY_MED 3700
Definition at line 70 of file tpm.h.
Referenced by vfnMoveCenter().
#define DUTY_MIN 1800
Definition at line 67 of file tpm.h.
Referenced by vfnMoveRight().
#define EDGE_PWM 0
Definition at line 61 of file tpm.h.
Referenced by vfnInitPWM().
#define PS_1 0
Definition at line 43 of file tpm.h.
#define PS_128 7
Definition at line 50 of file tpm.h.
#define PS_16 4
Definition at line 47 of file tpm.h.
Referenced by hc_sr04_init().
#define PS_2 1
Definition at line 44 of file tpm.h.
#define PS_32 5
Definition at line 48 of file tpm.h.
#define PS_4 2
Definition at line 45 of file tpm.h.
#define PS_64 6
Definition at line 49 of file tpm.h.
#define PS_8 3
Definition at line 46 of file tpm.h.
Referenced by vfnInitPWM().
#define TIMER 1000000
Definition at line 77 of file tpm.h.
#define TPM_CLK 1
Definition at line 40 of file tpm.h.
Referenced by hc_sr04_init(), hc_sr04_read(), and vfnInitPWM().
#define TPM_CNT_DIS 0
Definition at line 39 of file tpm.h.
Referenced by hc_sr04_init(), and hc_sr04_read().
#define TPM_EXT_CLK 2
Definition at line 41 of file tpm.h.
#define TPM_MCGIRCLK 3
Definition at line 37 of file tpm.h.
#define TPM_MODULE 52816
Definition at line 65 of file tpm.h.
Referenced by vfnInitPWM().
#define TPM_MUX 3
Definition at line 75 of file tpm.h.
Referenced by vfnSelectChannelPortPin().
#define TPM_OC_CLR TPM_CnSC_MSA_MASK|TPM_CnSC_ELSB_MASK
Definition at line 53 of file tpm.h.
#define TPM_OC_OUTH TPM_CnSC_MSB_MASK|TPM_CnSC_MSA_MASK|TPM_CnSC_ELSA_MASK
Definition at line 56 of file tpm.h.
#define TPM_OC_OUTL TPM_CnSC_MSB_MASK|TPM_CnSC_MSA_MASK|TPM_CnSC_ELSB_MASK
Definition at line 55 of file tpm.h.
#define TPM_OC_SET TPM_CnSC_MSA_MASK|TPM_CnSC_ELSA_MASK|TPM_CnSC_ELSB_MASK
Definition at line 54 of file tpm.h.
#define TPM_OC_TOGGLE TPM_CnSC_MSA_MASK|TPM_CnSC_ELSA_MASK
Definition at line 52 of file tpm.h.
#define TPM_OSCERCLK 2
Definition at line 36 of file tpm.h.
#define TPM_PLLFLL 1
Definition at line 35 of file tpm.h.
Referenced by hc_sr04_init(), and vfnInitPWM().
#define TPM_PWM_H TPM_CnSC_MSB_MASK|TPM_CnSC_ELSB_MASK
Definition at line 58 of file tpm.h.
Referenced by vfnInitPWM().
#define TPM_PWM_L TPM_CnSC_MSB_MASK|TPM_CnSC_ELSA_MASK
Definition at line 59 of file tpm.h.
Function Documentation
void set_pos (U16 angle)
Definition at line 44 of file tpm.c.
References set_TPM_CnV(), and TPM1_BASE_PTR.
Referenced by vfnMoveCenter(), vfnMoveLeft(), and vfnMoveRight().
void set_TPM_CnV (TPM_MemMapPtr TPMx, U08 channel, U16 value)
Definition at line 39 of file tpm.c.
References TPM_CnV_REG.
Referenced by set_pos().
void TPM_CH_init (TPM_MemMapPtr TPMx, U08 channel, U08 mode)
Definition at line 34 of file tpm.c.
References TPM_CnSC_REG.
Referenced by vfnInitPWM().
void TPM_init_PWM (TPM_MemMapPtr TPMx, U08 clock_source, U16 module, U08 clock_mode, U08 ps, U08 counting_mode)
Definition at line 14 of file tpm.c.
References SIM_SCGC6, SIM_SCGC6_TPM0_MASK, SIM_SCGC6_TPM1_MASK, SIM_SCGC6_TPM2_MASK, SIM_SOPT2, SIM_SOPT2_TPMSRC, TPM0_BASE_PTR, TPM1_BASE_PTR, TPM_MOD_REG, TPM_SC_CMOD, TPM_SC_CPWMS_MASK, TPM_SC_PS, and TPM_SC_REG.
Referenced by vfnInitPWM().
void vfnDelayTpm (U32 u32Delay)
Definition at line 49 of file tpm.c.
void vfnSelectChannelPortPin (ePorts port, U08 u08Pin)
Definition at line 9 of file tpm.c.
References TPM_MUX, and vfnConfigPortRegPins().
Referenced by vfnInitPWM().